// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace lbs {
class AddReqProto;
class AddReqProtoDefaultTypeInternal;
extern AddReqProtoDefaultTypeInternal _AddReqProto_default_instance_;
class AddResProto;
class AddResProtoDefaultTypeInternal;
extern AddResProtoDefaultTypeInternal _AddResProto_default_instance_;
class NearFriend;
class NearFriendDefaultTypeInternal;
extern NearFriendDefaultTypeInternal _NearFriend_default_instance_;
class ReqProto;
class ReqProtoDefaultTypeInternal;
extern ReqProtoDefaultTypeInternal _ReqProto_default_instance_;
class ResProto;
class ResProtoDefaultTypeInternal;
extern ResProtoDefaultTypeInternal _ResProto_default_instance_;
class SearchReqProto;
class SearchReqProtoDefaultTypeInternal;
extern SearchReqProtoDefaultTypeInternal _SearchReqProto_default_instance_;
class SearchResProto;
class SearchResProtoDefaultTypeInternal;
extern SearchResProtoDefaultTypeInternal _SearchResProto_default_instance_;
}  // namespace lbs

namespace lbs {

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_message_2eproto

// ===================================================================

class AddReqProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.AddReqProto) */ {
 public:
  AddReqProto();
  virtual ~AddReqProto();

  AddReqProto(const AddReqProto& from);

  inline AddReqProto& operator=(const AddReqProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddReqProto& default_instance();

  static inline const AddReqProto* internal_default_instance() {
    return reinterpret_cast<const AddReqProto*>(
               &_AddReqProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AddReqProto* other);

  // implements Message ----------------------------------------------

  inline AddReqProto* New() const PROTOBUF_FINAL { return New(NULL); }

  AddReqProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddReqProto& from);
  void MergeFrom(const AddReqProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddReqProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // @@protoc_insertion_point(class_scope:lbs.AddReqProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchReqProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.SearchReqProto) */ {
 public:
  SearchReqProto();
  virtual ~SearchReqProto();

  SearchReqProto(const SearchReqProto& from);

  inline SearchReqProto& operator=(const SearchReqProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchReqProto& default_instance();

  static inline const SearchReqProto* internal_default_instance() {
    return reinterpret_cast<const SearchReqProto*>(
               &_SearchReqProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SearchReqProto* other);

  // implements Message ----------------------------------------------

  inline SearchReqProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SearchReqProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SearchReqProto& from);
  void MergeFrom(const SearchReqProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SearchReqProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // double redius = 5;
  void clear_redius();
  static const int kRediusFieldNumber = 5;
  double redius() const;
  void set_redius(double value);

  // @@protoc_insertion_point(class_scope:lbs.SearchReqProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double redius_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.ReqProto) */ {
 public:
  ReqProto();
  virtual ~ReqProto();

  ReqProto(const ReqProto& from);

  inline ReqProto& operator=(const ReqProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqProto& default_instance();

  static inline const ReqProto* internal_default_instance() {
    return reinterpret_cast<const ReqProto*>(
               &_ReqProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ReqProto* other);

  // implements Message ----------------------------------------------

  inline ReqProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ReqProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReqProto& from);
  void MergeFrom(const ReqProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReqProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .lbs.AddReqProto addreq = 3;
  bool has_addreq() const;
  void clear_addreq();
  static const int kAddreqFieldNumber = 3;
  const ::lbs::AddReqProto& addreq() const;
  ::lbs::AddReqProto* mutable_addreq();
  ::lbs::AddReqProto* release_addreq();
  void set_allocated_addreq(::lbs::AddReqProto* addreq);

  // .lbs.SearchReqProto searchreq = 4;
  bool has_searchreq() const;
  void clear_searchreq();
  static const int kSearchreqFieldNumber = 4;
  const ::lbs::SearchReqProto& searchreq() const;
  ::lbs::SearchReqProto* mutable_searchreq();
  ::lbs::SearchReqProto* release_searchreq();
  void set_allocated_searchreq(::lbs::SearchReqProto* searchreq);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lbs.ReqProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::lbs::AddReqProto* addreq_;
  ::lbs::SearchReqProto* searchreq_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AddResProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.AddResProto) */ {
 public:
  AddResProto();
  virtual ~AddResProto();

  AddResProto(const AddResProto& from);

  inline AddResProto& operator=(const AddResProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddResProto& default_instance();

  static inline const AddResProto* internal_default_instance() {
    return reinterpret_cast<const AddResProto*>(
               &_AddResProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(AddResProto* other);

  // implements Message ----------------------------------------------

  inline AddResProto* New() const PROTOBUF_FINAL { return New(NULL); }

  AddResProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddResProto& from);
  void MergeFrom(const AddResProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddResProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:lbs.AddResProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NearFriend : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.NearFriend) */ {
 public:
  NearFriend();
  virtual ~NearFriend();

  NearFriend(const NearFriend& from);

  inline NearFriend& operator=(const NearFriend& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NearFriend& default_instance();

  static inline const NearFriend* internal_default_instance() {
    return reinterpret_cast<const NearFriend*>(
               &_NearFriend_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(NearFriend* other);

  // implements Message ----------------------------------------------

  inline NearFriend* New() const PROTOBUF_FINAL { return New(NULL); }

  NearFriend* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NearFriend& from);
  void MergeFrom(const NearFriend& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NearFriend* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double dist = 2;
  void clear_dist();
  static const int kDistFieldNumber = 2;
  double dist() const;
  void set_dist(double value);

  // double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lbs.NearFriend)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double dist_;
  double x_;
  double y_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchResProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.SearchResProto) */ {
 public:
  SearchResProto();
  virtual ~SearchResProto();

  SearchResProto(const SearchResProto& from);

  inline SearchResProto& operator=(const SearchResProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchResProto& default_instance();

  static inline const SearchResProto* internal_default_instance() {
    return reinterpret_cast<const SearchResProto*>(
               &_SearchResProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(SearchResProto* other);

  // implements Message ----------------------------------------------

  inline SearchResProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SearchResProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SearchResProto& from);
  void MergeFrom(const SearchResProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SearchResProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lbs.NearFriend friends = 1;
  int friends_size() const;
  void clear_friends();
  static const int kFriendsFieldNumber = 1;
  const ::lbs::NearFriend& friends(int index) const;
  ::lbs::NearFriend* mutable_friends(int index);
  ::lbs::NearFriend* add_friends();
  ::google::protobuf::RepeatedPtrField< ::lbs::NearFriend >*
      mutable_friends();
  const ::google::protobuf::RepeatedPtrField< ::lbs::NearFriend >&
      friends() const;

  // @@protoc_insertion_point(class_scope:lbs.SearchResProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lbs::NearFriend > friends_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lbs.ResProto) */ {
 public:
  ResProto();
  virtual ~ResProto();

  ResProto(const ResProto& from);

  inline ResProto& operator=(const ResProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResProto& default_instance();

  static inline const ResProto* internal_default_instance() {
    return reinterpret_cast<const ResProto*>(
               &_ResProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ResProto* other);

  // implements Message ----------------------------------------------

  inline ResProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ResProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResProto& from);
  void MergeFrom(const ResProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .lbs.AddResProto addres = 4;
  bool has_addres() const;
  void clear_addres();
  static const int kAddresFieldNumber = 4;
  const ::lbs::AddResProto& addres() const;
  ::lbs::AddResProto* mutable_addres();
  ::lbs::AddResProto* release_addres();
  void set_allocated_addres(::lbs::AddResProto* addres);

  // .lbs.SearchResProto searchres = 5;
  bool has_searchres() const;
  void clear_searchres();
  static const int kSearchresFieldNumber = 5;
  const ::lbs::SearchResProto& searchres() const;
  ::lbs::SearchResProto* mutable_searchres();
  ::lbs::SearchResProto* release_searchres();
  void set_allocated_searchres(::lbs::SearchResProto* searchres);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 code = 3;
  void clear_code();
  static const int kCodeFieldNumber = 3;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lbs.ResProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::lbs::AddResProto* addres_;
  ::lbs::SearchResProto* searchres_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 code_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AddReqProto

// double x = 3;
inline void AddReqProto::clear_x() {
  x_ = 0;
}
inline double AddReqProto::x() const {
  // @@protoc_insertion_point(field_get:lbs.AddReqProto.x)
  return x_;
}
inline void AddReqProto::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:lbs.AddReqProto.x)
}

// double y = 4;
inline void AddReqProto::clear_y() {
  y_ = 0;
}
inline double AddReqProto::y() const {
  // @@protoc_insertion_point(field_get:lbs.AddReqProto.y)
  return y_;
}
inline void AddReqProto::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:lbs.AddReqProto.y)
}

// -------------------------------------------------------------------

// SearchReqProto

// double x = 3;
inline void SearchReqProto::clear_x() {
  x_ = 0;
}
inline double SearchReqProto::x() const {
  // @@protoc_insertion_point(field_get:lbs.SearchReqProto.x)
  return x_;
}
inline void SearchReqProto::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:lbs.SearchReqProto.x)
}

// double y = 4;
inline void SearchReqProto::clear_y() {
  y_ = 0;
}
inline double SearchReqProto::y() const {
  // @@protoc_insertion_point(field_get:lbs.SearchReqProto.y)
  return y_;
}
inline void SearchReqProto::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:lbs.SearchReqProto.y)
}

// double redius = 5;
inline void SearchReqProto::clear_redius() {
  redius_ = 0;
}
inline double SearchReqProto::redius() const {
  // @@protoc_insertion_point(field_get:lbs.SearchReqProto.redius)
  return redius_;
}
inline void SearchReqProto::set_redius(double value) {
  
  redius_ = value;
  // @@protoc_insertion_point(field_set:lbs.SearchReqProto.redius)
}

// -------------------------------------------------------------------

// ReqProto

// int32 type = 1;
inline void ReqProto::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ReqProto::type() const {
  // @@protoc_insertion_point(field_get:lbs.ReqProto.type)
  return type_;
}
inline void ReqProto::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:lbs.ReqProto.type)
}

// int32 id = 2;
inline void ReqProto::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ReqProto::id() const {
  // @@protoc_insertion_point(field_get:lbs.ReqProto.id)
  return id_;
}
inline void ReqProto::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:lbs.ReqProto.id)
}

// .lbs.AddReqProto addreq = 3;
inline bool ReqProto::has_addreq() const {
  return this != internal_default_instance() && addreq_ != NULL;
}
inline void ReqProto::clear_addreq() {
  if (GetArenaNoVirtual() == NULL && addreq_ != NULL) delete addreq_;
  addreq_ = NULL;
}
inline const ::lbs::AddReqProto& ReqProto::addreq() const {
  // @@protoc_insertion_point(field_get:lbs.ReqProto.addreq)
  return addreq_ != NULL ? *addreq_
                         : *::lbs::AddReqProto::internal_default_instance();
}
inline ::lbs::AddReqProto* ReqProto::mutable_addreq() {
  
  if (addreq_ == NULL) {
    addreq_ = new ::lbs::AddReqProto;
  }
  // @@protoc_insertion_point(field_mutable:lbs.ReqProto.addreq)
  return addreq_;
}
inline ::lbs::AddReqProto* ReqProto::release_addreq() {
  // @@protoc_insertion_point(field_release:lbs.ReqProto.addreq)
  
  ::lbs::AddReqProto* temp = addreq_;
  addreq_ = NULL;
  return temp;
}
inline void ReqProto::set_allocated_addreq(::lbs::AddReqProto* addreq) {
  delete addreq_;
  addreq_ = addreq;
  if (addreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lbs.ReqProto.addreq)
}

// .lbs.SearchReqProto searchreq = 4;
inline bool ReqProto::has_searchreq() const {
  return this != internal_default_instance() && searchreq_ != NULL;
}
inline void ReqProto::clear_searchreq() {
  if (GetArenaNoVirtual() == NULL && searchreq_ != NULL) delete searchreq_;
  searchreq_ = NULL;
}
inline const ::lbs::SearchReqProto& ReqProto::searchreq() const {
  // @@protoc_insertion_point(field_get:lbs.ReqProto.searchreq)
  return searchreq_ != NULL ? *searchreq_
                         : *::lbs::SearchReqProto::internal_default_instance();
}
inline ::lbs::SearchReqProto* ReqProto::mutable_searchreq() {
  
  if (searchreq_ == NULL) {
    searchreq_ = new ::lbs::SearchReqProto;
  }
  // @@protoc_insertion_point(field_mutable:lbs.ReqProto.searchreq)
  return searchreq_;
}
inline ::lbs::SearchReqProto* ReqProto::release_searchreq() {
  // @@protoc_insertion_point(field_release:lbs.ReqProto.searchreq)
  
  ::lbs::SearchReqProto* temp = searchreq_;
  searchreq_ = NULL;
  return temp;
}
inline void ReqProto::set_allocated_searchreq(::lbs::SearchReqProto* searchreq) {
  delete searchreq_;
  searchreq_ = searchreq;
  if (searchreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lbs.ReqProto.searchreq)
}

// -------------------------------------------------------------------

// AddResProto

// -------------------------------------------------------------------

// NearFriend

// int32 id = 1;
inline void NearFriend::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 NearFriend::id() const {
  // @@protoc_insertion_point(field_get:lbs.NearFriend.id)
  return id_;
}
inline void NearFriend::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:lbs.NearFriend.id)
}

// double dist = 2;
inline void NearFriend::clear_dist() {
  dist_ = 0;
}
inline double NearFriend::dist() const {
  // @@protoc_insertion_point(field_get:lbs.NearFriend.dist)
  return dist_;
}
inline void NearFriend::set_dist(double value) {
  
  dist_ = value;
  // @@protoc_insertion_point(field_set:lbs.NearFriend.dist)
}

// double x = 3;
inline void NearFriend::clear_x() {
  x_ = 0;
}
inline double NearFriend::x() const {
  // @@protoc_insertion_point(field_get:lbs.NearFriend.x)
  return x_;
}
inline void NearFriend::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:lbs.NearFriend.x)
}

// double y = 4;
inline void NearFriend::clear_y() {
  y_ = 0;
}
inline double NearFriend::y() const {
  // @@protoc_insertion_point(field_get:lbs.NearFriend.y)
  return y_;
}
inline void NearFriend::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:lbs.NearFriend.y)
}

// -------------------------------------------------------------------

// SearchResProto

// repeated .lbs.NearFriend friends = 1;
inline int SearchResProto::friends_size() const {
  return friends_.size();
}
inline void SearchResProto::clear_friends() {
  friends_.Clear();
}
inline const ::lbs::NearFriend& SearchResProto::friends(int index) const {
  // @@protoc_insertion_point(field_get:lbs.SearchResProto.friends)
  return friends_.Get(index);
}
inline ::lbs::NearFriend* SearchResProto::mutable_friends(int index) {
  // @@protoc_insertion_point(field_mutable:lbs.SearchResProto.friends)
  return friends_.Mutable(index);
}
inline ::lbs::NearFriend* SearchResProto::add_friends() {
  // @@protoc_insertion_point(field_add:lbs.SearchResProto.friends)
  return friends_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::lbs::NearFriend >*
SearchResProto::mutable_friends() {
  // @@protoc_insertion_point(field_mutable_list:lbs.SearchResProto.friends)
  return &friends_;
}
inline const ::google::protobuf::RepeatedPtrField< ::lbs::NearFriend >&
SearchResProto::friends() const {
  // @@protoc_insertion_point(field_list:lbs.SearchResProto.friends)
  return friends_;
}

// -------------------------------------------------------------------

// ResProto

// int32 type = 1;
inline void ResProto::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ResProto::type() const {
  // @@protoc_insertion_point(field_get:lbs.ResProto.type)
  return type_;
}
inline void ResProto::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:lbs.ResProto.type)
}

// int32 id = 2;
inline void ResProto::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ResProto::id() const {
  // @@protoc_insertion_point(field_get:lbs.ResProto.id)
  return id_;
}
inline void ResProto::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:lbs.ResProto.id)
}

// int32 code = 3;
inline void ResProto::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 ResProto::code() const {
  // @@protoc_insertion_point(field_get:lbs.ResProto.code)
  return code_;
}
inline void ResProto::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:lbs.ResProto.code)
}

// .lbs.AddResProto addres = 4;
inline bool ResProto::has_addres() const {
  return this != internal_default_instance() && addres_ != NULL;
}
inline void ResProto::clear_addres() {
  if (GetArenaNoVirtual() == NULL && addres_ != NULL) delete addres_;
  addres_ = NULL;
}
inline const ::lbs::AddResProto& ResProto::addres() const {
  // @@protoc_insertion_point(field_get:lbs.ResProto.addres)
  return addres_ != NULL ? *addres_
                         : *::lbs::AddResProto::internal_default_instance();
}
inline ::lbs::AddResProto* ResProto::mutable_addres() {
  
  if (addres_ == NULL) {
    addres_ = new ::lbs::AddResProto;
  }
  // @@protoc_insertion_point(field_mutable:lbs.ResProto.addres)
  return addres_;
}
inline ::lbs::AddResProto* ResProto::release_addres() {
  // @@protoc_insertion_point(field_release:lbs.ResProto.addres)
  
  ::lbs::AddResProto* temp = addres_;
  addres_ = NULL;
  return temp;
}
inline void ResProto::set_allocated_addres(::lbs::AddResProto* addres) {
  delete addres_;
  addres_ = addres;
  if (addres) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lbs.ResProto.addres)
}

// .lbs.SearchResProto searchres = 5;
inline bool ResProto::has_searchres() const {
  return this != internal_default_instance() && searchres_ != NULL;
}
inline void ResProto::clear_searchres() {
  if (GetArenaNoVirtual() == NULL && searchres_ != NULL) delete searchres_;
  searchres_ = NULL;
}
inline const ::lbs::SearchResProto& ResProto::searchres() const {
  // @@protoc_insertion_point(field_get:lbs.ResProto.searchres)
  return searchres_ != NULL ? *searchres_
                         : *::lbs::SearchResProto::internal_default_instance();
}
inline ::lbs::SearchResProto* ResProto::mutable_searchres() {
  
  if (searchres_ == NULL) {
    searchres_ = new ::lbs::SearchResProto;
  }
  // @@protoc_insertion_point(field_mutable:lbs.ResProto.searchres)
  return searchres_;
}
inline ::lbs::SearchResProto* ResProto::release_searchres() {
  // @@protoc_insertion_point(field_release:lbs.ResProto.searchres)
  
  ::lbs::SearchResProto* temp = searchres_;
  searchres_ = NULL;
  return temp;
}
inline void ResProto::set_allocated_searchres(::lbs::SearchResProto* searchres) {
  delete searchres_;
  searchres_ = searchres;
  if (searchres) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lbs.ResProto.searchres)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace lbs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
